/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;
import org.apache.commons.cli.*;
public class App {
    Options options = new Options();
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
