/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;
import org.apache.commons.cli.*;
public class App {
    CommandLine cmd;

    public void init_cli(String[] args) throws ParseException {
        Options options = new Options();
        options.addOption("h", "help", false, "display the help page");
        CommandLineParser parser = new DefaultParser();
        cmd = parser.parse(options, args);
    }

    public void help(){
        if(cmd.hasOption("h")){
            System.out.println("this is the help page");
        }
    }

    public void lex(){
    }

    public static void main(String[] args) {
        App app = new App();
        try {
            app.init_cli(args);
        } catch (ParseException e){
            System.out.println(e.getMessage());
        }
        app.help();
        app.lex();
    }
}
