/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jw795;
import jw795.lexer.LexerAdapter;
import org.apache.commons.cli.*;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

public class Compiler {
    CommandLine cmd;

    public void init_cli(String[] args) throws ParseException {
        Options options = new Options();
        options.addOption("h", "help", false, "display the help page");
        options.addOption("lex", "lex", true, "perform lexical analysis on the input file");
        CommandLineParser parser = new DefaultParser();
        cmd = parser.parse(options, args);
    }

    public void help(){
        if(cmd.hasOption("h")){
            System.out.println("this is the help page");
        }
    }

    public void lex(){
        if(cmd.hasOption("lex")){
            // Initialize a reader given file name
            String fileName = cmd.getOptionValue("lex");

            try {
                // Generate token file
                Reader reader = new FileReader(fileName);
                LexerAdapter lexerAdapt = new LexerAdapter(reader, fileName);
                lexerAdapt.generateTokens();
            } catch (FileNotFoundException e) {
                System.out.println("File not found.????????");
            }
        }
    }

    public static void main(String[] args) {
        Compiler compiler = new Compiler();
        try {
            compiler.init_cli(args);
        } catch (ParseException e){
            System.out.println(e.getMessage());
        }
        compiler.help();
        compiler.lex();
    }
}
